version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=psql://postgres:postgres@db/postgres
      - CELERY_TASK_ALWAYS_EAGER=True
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "54330:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  webpack:
    build:
      context: .
      dockerfile: ./compose/local/webpack/Dockerfile
    container_name: komplexnizdravi_webpack
    image: komplexnizdravi_webpack
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  postgres_data:
