#!/bin/sh

set -o errexit
set -o nounset

echo "Waiting for postgres..."

while ! nc -z db 5432; do  # database container name and default port
  sleep 0.1
done

echo "PostgreSQL started"

python manage.py migrate --noinput

exec "$@"
