# Generated by Django 4.2.2 on 2023-06-09 01:37

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "obec",
                "verbose_name_plural": "obce",
            },
        ),
        migrations.CreateModel(
            name="CityArea",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.city")),
            ],
            options={
                "verbose_name": "dělení obcí",
                "verbose_name_plural": "dělení obcí",
            },
        ),
        migrations.CreateModel(
            name="CityPart",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.city")),
            ],
            options={
                "verbose_name": "část obce",
                "verbose_name_plural": "části obce",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "okres",
                "verbose_name_plural": "okresy",
            },
        ),
        migrations.CreateModel(
            name="OrpEntity",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "ORP",
                "verbose_name_plural": "ORP",
            },
        ),
        migrations.CreateModel(
            name="PouEntity",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "POU",
                "verbose_name_plural": "POU",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "kraj",
                "verbose_name_plural": "kraje",
            },
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.city")),
            ],
            options={
                "verbose_name": "ulice",
                "verbose_name_plural": "ulice",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                ("code", models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name="RUIAN")),
                ("conscription_number", models.CharField(default="", max_length=64)),
                ("street_number", models.CharField(default="", max_length=64)),
                ("provisional_number", models.CharField(default="", max_length=64)),
                ("zip_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField()),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.city")),
                (
                    "city_area1",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="data.cityarea"
                    ),
                ),
                (
                    "city_area2",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="data.cityarea"
                    ),
                ),
                (
                    "city_area3",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="data.cityarea"
                    ),
                ),
                (
                    "city_part",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="data.citypart"),
                ),
                ("district", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.district")),
                ("region", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.region")),
                ("street", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="data.street")),
            ],
            options={
                "verbose_name": "adresa",
                "verbose_name_plural": "adresy",
            },
        ),
        migrations.AddField(
            model_name="district",
            name="region",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.region"),
        ),
        migrations.AddField(
            model_name="city",
            name="district",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.district"),
        ),
        migrations.AddField(
            model_name="city",
            name="orp",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.orpentity"),
        ),
        migrations.AddField(
            model_name="city",
            name="pou",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="data.pouentity"),
        ),
    ]
