# Generated by Django 4.2.2 on 2023-06-09 02:14

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_alter_city_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="district",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="data.district"),
        ),
    ]
